# 服务器本地端口
#section对象，使用ConfigMgr管理
[GateServer] 
#sectioninfo对象，使用SectionInfo管理
Port = 8080	
# Varify服务器端口
[VarifyServer]
Host = 127.0.0.1
Port = 50051
[StatusServer]
Host = 127.0.0.1
Port = 50052
[MySQL]
Host = 127.0.0.1
Port = 3308
User = root
Passwd = 123456
Schema = roottest
# 博主云服务IP和端口
[Redis]
Host = 81.68.86.146
Port = 6380
Passwd = 123456
